### ISSUE TITLE
Typo prevents use on Linux

### ISSUE THREAD

**Issue by jcw** [Digilent/digilent-vivado-scripts#11]
This line contains a backslash:

https://github.com/Digilent/digilent-vivado-scripts/blob/ffa3f4f7bea46dc30645e1b618701ea3806b7707/git_vivado.py#L104

Changing it to a forward slash makes it work on Linux (as well as Windows, I expect).

**Comment by artvvb** [comment]
Resolved by https://github.com/Digilent/digilent-vivado-scripts/commit/5828b2f3a0e9cb14931115f6fe9a5503ef947c56
