### ISSUE TITLE
Updating to Vivado 2020.2

### ISSUE THREAD

**Issue by acklay4** [Digilent/digilent-vivado-scripts#18]
Since Xilinx did change some parts of their folder namings, the checkout command is no longer working for Vivado HLS 2020.2: 

`[acklay4@manjaro digilent-vivado-scripts] $ python3 git_vivado.py checkout -v 2020.2`
throws:
`Error: XSCT not installed at /opt/Xilinx/Vitis/2020.2/bin/xsct`
which is, in fact correct, since a short `[acklay4@manjaro digilent-vivado-scripts] $ ls /opt/Xilinx/` brings up:
`Docnav    Vitis_HLS    Vivado    xic`
and if we navigate deeper into Vitis_HLS it brings
`[acklay4@manjaro digilent-vivado-scripts] $ ls /opt/Xilinx/Vitis_HLS/2020.2/bin/`
`unwrapped    apcc    hlsArgs.sh    ldlibpath.sh    loader    rdiArgs.sh    setEnvAndRunCmd.sh    setupEnv.sh    unsetldlibpath.sh    vitis_hls    xcd    xlicdiag    xrcserver` where `unwrapped` is a folder.
Thank you :)

**Comment by artvvb** [comment]
The error should be resolved by commit e0825e49379f46d673a2803675a93e510d8b55ef. An unnecessary check for the Vitis xsct executable was removed.

Note that neither Vivado HLS nor Vitis HLS is supported by these scripts.
