### ISSUE TITLE
project_info.tcl is insufficient for versioning project settings

### ISSUE THREAD

**Issue by elodg** [Digilent/digilent-vivado-scripts#4]
@artvvb 

Capturing any and all Vivado project settings one would need is impossible with the current scripts.
For example, Synthesis and Implementation strategies are not saved anywhere.

Checkin overwrites project_info with a very limited set of automatically extracted project settings. Even if strategies were captured there, project_info.tcl is sourced too early by checkout when runs are not created yet.

I see two possible solutions:

- either create hooks in checkout to some manually managed tcl scripts where any further customization can be stored

- or delegate all checkout functionality to a script versioned in the project repo (à la create_project.tcl), which can be created, if missing, with default content upon checkin, but managed manually afterwards.

**Comment by artvvb** [comment]
@elodg Is the fix from https://github.com/Digilent/digilent-vivado-scripts/commit/215db1d8684bb719681942dd8d8b67ec2243f45e sufficient?

**Comment by elodg** [comment]
t is.
